export declare const $JSONSchema: unique symbol;
export type $JSONSchema = typeof $JSONSchema;
export type JSONSchemaType = "string" | "number" | "integer" | "boolean" | "object" | "array" | "null";
export type JSONSchemaRaw = boolean | Readonly<{
    [$JSONSchema]?: $JSONSchema;
    $id?: string | undefined;
    $ref?: string | undefined;
    $schema?: string | undefined;
    $comment?: string | undefined;
    type?: JSONSchemaType | readonly JSONSchemaType[];
    const?: unknown;
    enum?: unknown;
    multipleOf?: number | undefined;
    maximum?: number | undefined;
    exclusiveMaximum?: number | undefined;
    minimum?: number | undefined;
    exclusiveMinimum?: number | undefined;
    maxLength?: number | undefined;
    minLength?: number | undefined;
    pattern?: string | undefined;
    items?: JSONSchemaRaw | readonly JSONSchemaRaw[];
    additionalItems?: JSONSchemaRaw;
    contains?: JSONSchemaRaw;
    maxItems?: number | undefined;
    minItems?: number | undefined;
    uniqueItems?: boolean | undefined;
    maxProperties?: number | undefined;
    minProperties?: number | undefined;
    required?: readonly string[];
    properties?: Readonly<Record<string, JSONSchemaRaw>>;
    patternProperties?: Readonly<Record<string, JSONSchemaRaw>>;
    additionalProperties?: JSONSchemaRaw;
    unevaluatedProperties?: JSONSchemaRaw;
    dependencies?: Readonly<Record<string, JSONSchemaRaw | readonly string[]>>;
    propertyNames?: JSONSchemaRaw;
    if?: JSONSchemaRaw;
    then?: JSONSchemaRaw;
    else?: JSONSchemaRaw;
    allOf?: readonly JSONSchemaRaw[];
    anyOf?: readonly JSONSchemaRaw[];
    oneOf?: readonly JSONSchemaRaw[];
    not?: JSONSchemaRaw;
    format?: string | undefined;
    contentMediaType?: string | undefined;
    contentEncoding?: string | undefined;
    definitions?: Readonly<Record<string, JSONSchemaRaw>>;
    title?: string | undefined;
    description?: string | undefined;
    default?: unknown;
    readOnly?: boolean | undefined;
    writeOnly?: boolean | undefined;
    examples?: readonly unknown[];
    nullable?: boolean;
}>;
export type JSONSchemaReference = JSONSchemaRaw & Readonly<{
    $id: string;
}>;
